---
title: "Last Lab Quiz Markdown!!!"
author: "Mackenzie Seasons"
date: '2016-11-22'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I examined the extent to which exam grades (E) were predicted by anxiety (A) and preparation (P). As indicated in Table 1, when the predictors were examined individually, there was a moderate positive relation between anxiety and exam grades, *r* = .69, 95% CI[.64, .73], such that as anxiety increased exam grades increased. There was a moderate positive relation between preparation and exam grades, *r* = .49, 95% CI[.42, .56], such that as preparation increased so did exam grades. Further, there was a weak to moderate positive relation between anxiety and preparation, *r* = .23, 95% CI[.15, .31], such that as anxiety increased, so did preparation.

I used moderated multiple regression to test the extent to which the relation between anxiety and exam grades depended on the amount of exam preparation. I assessed this moderation by examining the interaction between anxiety and preparation using centered predictors (consistent with the recommendations of Cohen, Cohen, West, and Aiken (2003)), see Table 2. Together the predictors (anxiety, preparation, and their product) accounted for a moderate amount of variance in exam grades, $*R^2*=.617$, 95% CI[.57, .66], *p* < .01. The p-value for the anxiety by preparation product term was below .01, t(496)= 6.06, p < .0001, which suggests the presence of an interaction. As indicated by the squared semi-partial correlation for the product term, the proportion of variance accounted for was small, $sr^2=.03$, 95% CI[.01, .05]. This means that preparation accounts for only an additional 3% of the variance in exam grades beyond anxiety alone. In light of this interaction, the the regression surface was explored with simple-slope analyses.

The regression surface is presented in Figure 1 and the simple-slope cross-sections are presented in Figure 2. When preparation was high (i.e., +1 SD) there was a positive relationship between anxiety and exam grades, $b=19.49$, 95% CI[17.50, 21.48], t(496)=19.255, *p* < .001, see Equation 1 below. When preparation was low (i.e., -1 SD), there was also a positive relation between anxiety and exam grades such that as anxiety increased exam grades increased also, $b=11.02$, 95% CI[9.08, 12.96], *t*(496)=11.16, *p* < .001, see Equation 2 below.

$\hat{E}= 19.49A + 55.90$ (1)

$\hat{E}= 11.16A + 42.52$ (2)

The relation between anxiety and exam grades appears to be moderated by the extent to which students prepared for the exam. If students prepared extensively for the exam, high anxiety levels was related to improved exam performance. Additionally, if students did not prepare extensively for the exam, high anxiety levels resulted in increased exam performance.